import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Abhay Prajapati",
  description: "Generated by create next app",
};

console.log("render layout")

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <div>hello iam layout</div> */}
        <div style={{ background: "linear-gradient(90deg, rgba(1,14,35,1) 49%, rgba(67,61,66,1) 100%, rgba(15,15,150,1) 100%)" }}>
        <Navbar />
        {children}
        </div>
      </body>
    </html>
  );
}
